# post automation_setup.yml, we don't need this anymore...
# ansible_ssh_user: "{{ vault_ansible_ssh_user }}"

# SSH vars
environ:  "stage" # dev || stage || prod
debugging: true
login_user_passphrase: "{{ vault_login_user_passphrase }}"
domain: "library.jhu.edu"

# db vars
db_name: "{{ vault_db_name }}"
db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"

# admin vars
# members of this list will not be anonymized (no additional permissions granted):
admin_users: "{{ vault_admin_users }}"

# mail vars
smtp_host: "{{ vault_smtp_host }}"

# assetstore vars
# stores_subdir:  "vireo_data_stage"
