copy# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# meta vars
project:        "vireo-ansible"
version:        "0.2.0"
debugging:      false

# SSH vars
login_user:             "deploy"
login_group:            "{{ login_user }}"
login_user_key:         "{{ project }}_{{ environ }}"
create_login_user_key:  true

app_user: "vireo"
app_group: "{{ app_user }}"


# db vars
postgres_user:    "postgres"
pgdata:           "/var/lib/pgsql/data/"
pgbin:            ""
db_backup_file:   "{{ db_name }}_{{ environ }}_backup.sql"
copy_db_name:     "{{ db_name }}_copy"
copy_backup_file: "{{ copy_db_name }}_backup.sql"
netid_suffix:     "@johnshopkins.edu"
retain_backup:    true

# admin vars
email_domain_name: "jhu.edu"

# install vars
vireo_install_dir: "/opt"
vireo_install: "{{ vireo_install_dir }}/Vireo"

# config vars
country: "USA"

# data transform queries
transform_queries:
- "institutionalid_from_netid.sql.j2"
- "anonymize_db.sql.j2"

# assetstore vars
remote_stores_available: true
# sam.mse.jhu.edu:/files/etd                      /mnt/ETD                nfs4            rw,intr,noatime         0 0
stores_fstab:
- name:         "/mnt/ETD"
  src:          "sam.mse.jhu.edu:/files/etd"
  fstype:       "nfs4"
  opts:         "rw,intr,noatime"
  state:        "mounted"
stores_subdir:  "vireo_data_prod"
assetstores:
  - attachments
  - deposits
