# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# meta vars
project:        "vireo-ansible"
version:        "0.2.0"
debugging:      false

# SSH vars
use_master_user:        true
remote_user:            "{{ lookup('ini', 'remote_user section=cross-project file=~/.ansible.ini') }}"
login_user:             "{{ lookup('ini', 'login_user section=cross-project file=~/.ansible.ini') }}"
# login_group_gid:        2042
# login_user_uid:         2042
login_user_key:         "jhu_ssh_key"
create_login_user_key:  false
login_user_grant_sudo:  false

ssh_settings:
- regexp: "^PermitRootLogin"
  setting: "PermitRootLogin no"
- regexp: "^DenyUsers deploy"
  setting: "DenyUsers deploy"

app_user:       "vireo"
app_group:      "{{ app_user }}"
app_group_gid:  501
app_user_uid:   500

# db vars
postgres_user:    "postgres"
pgdata:           "/var/lib/pgsql/data/"
pgbin:            ""
db_backup_file:   "{{ db_name }}_{{ environ }}_backup.sql"
copy_db_name:     "{{ db_name }}_copy"
copy_backup_file: "{{ copy_db_name }}_backup.sql"
netid_suffix:     "@johnshopkins.edu"
retain_backup:    true
postgres_version_major: 8
postgres_version_minor: 4
postgres_legacy:        true
postgres_extra_packages: []
postgres_extensions: []
db_name:                "{{ vault_db_name }}"
db_user:                "{{ vault_db_user }}"
db_pass:                "{{ vault_db_pass }}"
db_create_users:        true
db_users:
  - user:               "{{ db_user }}"
    pass:               "{{ db_pass }}"
    flags:              "CREATEDB,NOSUPERUSER,NOCREATEROLE"
db_create_databases:    true
db_databases:
  - name:               "{{ db_name }}"
    encoding:           "UTF-8"
    owner:              "{{ db_user }}"

# TODO: use firewall config to limit access to particular IPs
# NOTE: samenet isn't supported by postgres 8.x
# TODO: entries will be added in the reverse of the order in which they are listed here
# subsequent runs with new entries will add the new ones to the top of the file.
# therefore, the order of entries is essentially unpredictable.
# consider modifying postgres role to whack pg_hba.conf before adding entries.
# this may make entries and templates mutually exclusive, but otherwise,
# this will be more intuitive, idempotent, and predictable
# TODO: the db_refresh playbooks have the potential to whack these entries. fix
postgres_hba_entries:
- type:                 "host"
  database:             "{{ db_name }}"
  user:                 "{{ db_user }}"
  address:              "127.0.0.1/32"
  method:               "md5"
- type:                 "local"
  database:             "{{ db_name }}"
  user:                 "{{ db_user }}"
  method:               "md5"
- type:                 "local"
  database:             "all"
  user:                 "postgres"
  method:               "ident"

# NOTE: comment out for initial or re-configuration
# vireo_db_config_files: []

# admin vars
email_domain_name: "jhu.edu"

# install vars
vireo_install_dir:  "/opt"
vireo_install:      "{{ vireo_install_dir }}/Vireo"

# config vars
vireo_environ:        "{{ environ | default('default') }}"
# TODO: refactor to one var
vireo_mail_smtp_host: "{{ vault_smtp_host | default('127.0.0.1') }}"
country: "USA"

# apache vars
vireo_proxy:                    true # currently, only proxying through Apache is supported
apache_https:                   true
apache_remove_welcome:          false
hostname:                       "vireo-{{ environ }}"
domainname:                     "library.jhu.edu"
apache_config_file:             "/etc/httpd/conf.d/01_{{ hostname }}.conf"
# TODO: change after upgrading
# Centos6 apache package version is old, so we need to take steps to
# disable SSL compression and use a legacy configuration
apache_legacy_configuration:    true
ssl_self_sign_cert:             true
ssl_support_legacy_clients:     false

# data transform queries
transform_queries:
- "institutionalid_from_netid.sql.j2"
- "anonymize_db.sql.j2"

# assetstore vars
remote_stores_available: true
# sam.mse.jhu.edu:/files/etd                      /mnt/ETD                nfs4            rw,intr,noatime         0 0
stores_fstab:
- name:         "/mnt/ETD"
  src:          "sam.mse.jhu.edu:/files/etd"
  fstype:       "nfs4"
  opts:         "rw,intr,noatime"
  state:        "mounted"
stores_subdir:  "vireo_data_prod"
assetstores:
  - attachments
  - deposits

# custom export formats
custom_formats:
- "dspace_mets_jhu"
- "ProquestUMI_0"
- "ProquestUMI_1"
- "ProquestUMI_2"

# shib vars
vireo_shibbolize:                 true # if true, vireo_proxy must also be true
# TODO: application mode also controls shib mock. decouple.
# https://github.com/dheles/Vireo/commit/03df0104748bea3994a7997fe024c29bf797584d
vireo_application_mode:           "prod" # [dev, prod]
shib_install:                     false
shib_backup_configs:              true
shib_sp_cert:                     "{{ vault_shib_sp_cert }}"
shib_sp_key:                      "{{ vault_shib_sp_key }}"
shib_repo_name:                   "security_shibboleth"
shib_repo_description:            "Shibboleth (CentOS_CentOS-6)"
shib_repo_mirrorlist:             "https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_CentOS-6"
shib_repo_gpgkey:                 "https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key"
shib_virtualhost_template:        "templates/shib-virtualhost.j2"
shib_attribute_template:          "templates/vault-shib-attribute-map.xml"
shib_config_template:             "templates/vault-shibboleth2.xml"
shib_entity_id:                   "{{ vault_shib_entity_id }}"
shib_idp_entity_id:               "{{ vault_shib_idp_entity_id }}"
shib_contact:                     "{{ vault_shib_contact }}"
shib_idp_metadata:
- filename: "idp-metadata.xml"
  src: "templates/vault-idpjhedu-metadata.xml"
vireo_shib_config:                "shibboleth_conf_block.j2"
shib_firstname_attribute:         "givenname" # lowercase: givenname | jhegivennamepreferred

# branding vars:
vireo_logos:
- "files/left-logo"
- "files/right-logo"

# testing vars
set_up_tests:   false
