# post automation_setup.yml, we don't need this anymore...
# ansible_ssh_user: "vagrant"

# meta vars
environ:  "dev" # dev || stage || prod
debugging: true

# private vars
login_user_passphrase: "{{ vault_login_user_passphrase }}"

# play_version_minor:         4
# play_version_patch:         6
# play_checksum_algorithm:    "sha1" # sha1 | sha256 | md5
# play_checksum:    "d5fc42c0b63b03bfeb9859f5d47e2a20"

# assetstore vars
remote_stores_available:  false
stores_fstab:             []
# stores_subdir:            ""
# stores_fstab:
# - name:         "/mnt/ETD"
#   src:          "10.51.30.1:/Users/dheles/Source/vireo-ansible/mount"
#   fstype:       "nfs"
#   opts:         "rw,intr,noatime"
#   state:        "absent" #"mounted"

# SSH vars
login_password:         "{{ lookup('ini', 'login_password section=dev file=~/.ansible.ini') }}"
login_user_grant_sudo:  true

# user ids
vagrant_group_gid:  1001
vagrant_user_uid:   1001

# config vars
# domainname:                 "test"
vireo_application_baseUrl:  "https://{{ hostname }}.{{ domainname }}/"

# shib vars
shib_install:                     true
shib_entity_id:                   "https://vireo-dev.library.jhu.edu/shibboleth"
shib_firstname_attribute:         "jhegivennamepreferred" # lowercase: givenname | jhegivennamepreferred
