# post automation_setup.yml, we don't need this anymore...
# ansible_ssh_user: "vagrant"

# meta vars
environ:  "dev" # dev || stage || prod

# private vars
login_user_passphrase: "{{ vault_login_user_passphrase }}"
