---
- name: customize export formats
  hosts: app
  become: yes

  tasks:
    - name: deploy custom export formats
      template:
        src: templates/{{ item }}.xml.j2
        dest: "{{ vireo_install }}/conf/formats/{{ item }}.xml"
      with_items: "{{ custom_formats }}"

    - name: modified application context
      template:
        src: templates/application-context.xml.j2
        dest: "{{ vireo_install }}/conf/application-context.xml"
